import { config } from "@tamagui/config/v3";
import { createTamagui } from "tamagui";

const tamaguiConfig = createTamagui({
  ...config,
  themes: {
    light: {
      background: "#FFFFFF",
      backgroundHover: "#F8F9FA",
      backgroundPress: "#F3F4F6",
      backgroundFocus: "#F8F9FA",
      backgroundStrong: "#333333",
      backgroundTransparent: "rgba(255, 255, 255, 0)",
      color: "#333333",
      colorHover: "#1F1F1F",
      colorPress: "#1F1F1F",
      colorFocus: "#333333",
      colorTransparent: "rgba(51, 51, 51, 0)",
      borderColor: "#E5E7EB",
      borderColorHover: "#D1D5DB",
      borderColorFocus: "#CEDE6C",
      borderColorPress: "#D1D5DB",
      placeholderColor: "#9FA1A4",
      primary: "#CEDE6C",
      primaryHover: "#B8C85A",
      primaryPress: "#A2B248",
      primaryFocus: "#CEDE6C",
      secondary: "#F29131",
      secondaryHover: "#E07B1A",
      secondaryPress: "#C96A10",
      secondaryFocus: "#F29131",
      success: "#22C55E",
      warning: "#F29131",
      error: "#EF4444",
    },
    dark: {
      background: "#1A1A1A",
      backgroundHover: "#2A2A2A",
      backgroundPress: "#0F0F0F",
      backgroundFocus: "#2A2A2A",
      backgroundStrong: "#F9FAFB",
      backgroundTransparent: "rgba(26, 26, 26, 0)",
      color: "#F9FAFB",
      colorHover: "#FFFFFF",
      colorPress: "#FFFFFF",
      colorFocus: "#F9FAFB",
      colorTransparent: "rgba(249, 250, 251, 0)",
      borderColor: "#374151",
      borderColorHover: "#4B5563",
      borderColorFocus: "#D4E67A",
      borderColorPress: "#4B5563",
      placeholderColor: "#6B7280",
      primary: "#D4E67A",
      primaryHover: "#DEF08A",
      primaryPress: "#CEDE6C",
      primaryFocus: "#D4E67A",
      secondary: "#F9A352",
      secondaryHover: "#FAB372",
      secondaryPress: "#F29131",
      secondaryFocus: "#F9A352",
      success: "#4ADE80",
      warning: "#F9A352",
      error: "#F87171",
    },
    light_highcontrast: {
      background: "#FFFFFF",
      backgroundHover: "#F0F0F0",
      backgroundPress: "#E8E8E8",
      backgroundFocus: "#F0F0F0",
      backgroundStrong: "#000000",
      backgroundTransparent: "rgba(255, 255, 255, 0)",
      color: "#000000",
      colorHover: "#000000",
      colorPress: "#000000",
      colorFocus: "#000000",
      colorTransparent: "rgba(0, 0, 0, 0)",
      borderColor: "#000000",
      borderColorHover: "#000000",
      borderColorFocus: "#C54A2C",
      borderColorPress: "#000000",
      placeholderColor: "#4A4A4A",
      primary: "#C54A2C",
      primaryHover: "#A33E24",
      primaryPress: "#8B3420",
      primaryFocus: "#C54A2C",
      secondary: "#D4A02A",
      secondaryHover: "#B88822",
      secondaryPress: "#9C711A",
      secondaryFocus: "#D4A02A",
      success: "#1B5E20",
      warning: "#D4A02A",
      error: "#B71C1C",
    },
    dark_highcontrast: {
      background: "#000000",
      backgroundHover: "#1A1A1A",
      backgroundPress: "#0A0A0A",
      backgroundFocus: "#1A1A1A",
      backgroundStrong: "#FFFFFF",
      backgroundTransparent: "rgba(0, 0, 0, 0)",
      color: "#FFFFFF",
      colorHover: "#FFFFFF",
      colorPress: "#FFFFFF",
      colorFocus: "#FFFFFF",
      colorTransparent: "rgba(255, 255, 255, 0)",
      borderColor: "#FFFFFF",
      borderColorHover: "#FFFFFF",
      borderColorFocus: "#FF9270",
      borderColorPress: "#FFFFFF",
      placeholderColor: "#B0B0B0",
      primary: "#FF9270",
      primaryHover: "#FFA080",
      primaryPress: "#FF8460",
      primaryFocus: "#FF9270",
      secondary: "#FFE380",
      secondaryHover: "#FFE890",
      secondaryPress: "#FFD870",
      secondaryFocus: "#FFE380",
      success: "#69F0AE",
      warning: "#FFE380",
      error: "#FF5252",
    },
  },
});

export type Conf = typeof tamaguiConfig;

declare module "tamagui" {
  interface TamaguiCustomConfig extends Conf {}
}

export default tamaguiConfig;
